version: "3.4"

services:
  webserver:
    build:
      context: ./.docker/bin/php73
      network: host
    container_name: "${DOCKER_NAME_PREFIX}_webserver"
    links:
      - database
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT-80}:80"
      - "${HOST_MACHINE_STENCIL_HOST_PORT-3333}:3333"
      # - "${HOST_MACHINE_SECURE_HOST_PORT-443}:443"
    volumes:
      - ./laravel:/var/www/html
      - ./stencil:/var/www/stencil
      - ./.docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/config/php/vhosts:/etc/apache2/sites-enabled
      - ./.docker/logs/apache2:/var/log/apache2
  database:
    build:
      context: "./.docker/bin/mysql"
    container_name: "${DOCKER_NAME_PREFIX}_database"
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      # persisted volume not used due to performance, uncomment to enable
      # - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql:delegated
      - ./.docker/logs/mysql:/var/log/mysql
      - ./.docker/data/mysqlbackup:/var/backups
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
