import { Component, h, Prop, State, Element, Listen, Host } from '@stencil/core';
import Isemail from 'isemail';
import serialize from 'form-serialize';
import { ToastService } from '../../../../services/toast.service';
import { APIService } from '../../../../services/api.service';
import { RouterService } from '../../../../services/router.service';
import { LoadingService } from '../../../../services/loading.service';
import { i18nService } from '../../../../services/i18n.service';

@Component({
    tag: 'form-reset-password',
    styleUrl: 'form-reset-password.scss'
})
export class FormResetPassword {
    @Element() el: HTMLElement;

    /**
     * The password reset token generated by the api
     */
    @Prop() token!: string;

    @State() errors: string[] = [];
    @State() rerender: number = 0;

    @Listen('localeUpdate', { target: 'body' })
    localeUpdated() {
        this.rerender++;
    }

    form: HTMLFormElement;
    isDirty: boolean = false;

    validateDirtyInputs() {
        if (!this.isDirty) {
          return true;
        }
    
        return this.validate();
    }
    
    validate() {
        const errors = [];
        let results = serialize(this.form, { hash: true, empty: true });
    
        if (!results.email) {
            errors.push(i18nService.get('errors.invalidemail', this.el));
        }
        else {
          if (!Isemail.validate(results.email)) {
            errors.push(i18nService.get('errors.invalidemail', this.el));
          }
        }

        if (!results.password) {
            errors.push(i18nService.get('errors.nopassword', this.el));
        }
        else {
            if (results.password !== results.password_confirmation) {
                errors.push(i18nService.get('errors.passwordmatch', this.el));
            }
        }
    
        this.errors = errors;
    
        return !errors.length;
    }

    async handleSubmit(e) {
        e.preventDefault();

        this.isDirty = true;

        if (!this.validate()) {
            return;
        }

        await LoadingService.showLoading();

        let results = serialize(this.form, { hash: true, empty: true });

        try {
            let response = await APIService.post({ endpoint: 'reset-password', data: results });

            if (response.ok) {
                RouterService.forward(RouterService.getRoute('login'));
                ToastService.success(i18nService.get('messages.success', this.el));
            }
            else {
                ToastService.error(i18nService.get('errors.api', this.el));
            }
        } catch (e) {
            ToastService.error(e.message);
        }

        await LoadingService.hideLoading();
    }

    render() {
        return (
            <Host data-rerender={this.rerender}>
                <form
                    class="pure-form pure-form-aligned"
                    onSubmit={e => this.handleSubmit(e)}
                    ref={el => this.form = el as HTMLFormElement }
                >
                    <fieldset>
                        <h1>{ i18nService.get('title', this.el) }</h1>
                        <div class="pure-control-group">
                            <label htmlFor="reset-password-form-password">{ i18nService.get('password', this.el) }</label>
                            <input
                                id="reset-password-form-password"
                                type="password"
                                name="password"
                                value=""
                                class="block"
                                onChange={() => this.validateDirtyInputs() }
                            />
                        </div>

                        <div class="pure-control-group">
                            <label htmlFor="reset-password-form-password2">{ i18nService.get('passwordagain', this.el) }</label>
                            <input
                                id="reset-password-form-password2"
                                type="password"
                                name="password_confirmation"
                                value=""
                                class="block"
                                onChange={() => this.validateDirtyInputs() }
                            />
                        </div>

                        <div class="pure-controls">

                            {
                                this.errors.length ? <div class="errors">
                                {
                                    this.errors.map(e => <div>{e}</div>)
                                }
                                </div>
                                : null
                            }

                            <input type="hidden" name="token" value={this.token} />
                            <input type="hidden" name="email" value={ RouterService.getQueryParam('email') } />

                            <button type="submit" class="pure-button pure-button-primary">
                                { i18nService.get('submit', this.el) }
                            </button>
                        </div>
                    </fieldset>
                </form>
            </Host>
        )
    }
}